# TODO R Execute LR
rm(list = ls())
library(readr)
library(dplyr)
library(purrr)
library(rustr)
library(cli)
df <- return_df(mtcars)
print(df)
iris = mutate(iris, str = as.character(Species))
df <- return_df(iris)
print(df)