# TODO R Execute LR
rm(list = ls())
library(readr)
library(dplyr)
library(purrr)
library(rustr)
library(cli)
# mtcars <- map_dfr(1:100, ~ as_tibble(mtcars))
# mtcars <- map_dfr(1:30, ~ as_tibble(mtcars))
results <- execute_lr(mtcars, "am")
# results <- execute_lr(iris, 'am')
