# TODO R Execute LR
rm(list = ls())
library(readr)
library(dplyr)
library(purrr)
library(redpul)
library(cli)
iris <- mutate(iris, str = as.character(Species))
big_iris <- map_df(1:1000, ~iris)
df <- return_df(iris, dtypes = map_chr(big_iris, typeof))
print(df)
