# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustr_wrappers", use_symbols = TRUE, package_name = "rustr")

#' @docType package
#' @usage NULL
#' @useDynLib rustr, .registration = TRUE
NULL

#' execute_lr
#' TODO execute_lf
#'
#' ## Linear Regression from Rus
#'
#' @export
execute_lr <- function(dataset) .Call(wrap__execute_lr, dataset)

