# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustr_wrappers", use_symbols = TRUE, package_name = "rustr")

#' @docType package
#' @usage NULL
#' @useDynLib rustr, .registration = TRUE
NULL

#' return_df
#' @export return_df
return_df <- function(dataset = NULL) {
  types <- map_chr(dataset, typeof)
  row.names(dataset) <- NULL
  cli_alert_info("Before .Call")
  out <- .Call(
    wrap__return_df, dataset, types
  )
  cli_alert_info("After .Call")
  out
}
