# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_redpul_wrappers", use_symbols = TRUE, package_name = "redpul")

#' @docType package
#' @usage NULL
#' @useDynLib redpul, .registration = TRUE
NULL

#' return_df
#' TODO execute_lf
#'
#' ## Linear Regression from Rust
#'
#' @export
return_df <- function(dataset, dtypes) .Call(wrap__return_df, dataset, dtypes)

